# WARNING:
# THIS FILE IS NOT CURRENTLY USED BY `docker compose` (THE DOCKER CLI VERSION)
# IT IS ONLY USED BY `docker-compose` (THE STANDALONE TOOL)
version: '3.1'
services:

  # The REST / GraphQL API
  #  api:
  #    build:
  #      context: .
  #      dockerfile: docker/api/Dockerfile

  # The SQL database
  db:
    # Expose the ports for local development
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: dsa_pgadmin
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 5439:80
